# -*- coding: utf-8 -*-
"""Final_product_recommended_sys_(1) (1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sey352MtAs8JQcbi1SK_LHbRsxSdsr7B

# Product Recommendation System

## 1. Data Loading & Preprocessing

### 1.1 Import libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics.pairwise import cosine_similarity
import networkx as nx

"""### 1.2 Load dataset"""

df=pd.read_csv('walmart.tsv',sep='\t')

"""### 1.3 Handle missing values"""

df.info()

df.head()

df = df[['Uniq Id','Product Id', 'Product Rating', 'Product Reviews Count', 'Product Category', 'Product Brand', 'Product Name', 'Product Image Url', 'Product Description', 'Product Tags']]

df.shape

df.isnull().sum()

df = df.dropna(subset=["Uniq Id", "Product Id", "Product Name"])
df["Product Brand"] = df["Product Brand"].fillna("")
df["Product Category"] = df["Product Category"].fillna("")
df["Product Description"] = df["Product Description"].fillna("")
df["Product Tags"] = df["Product Tags"].fillna("")
df["Product Rating"] = pd.to_numeric(df["Product Rating"], errors="coerce").clip(0,5)
df["Product Rating"] = df["Product Rating"].fillna(df["Product Rating"].median())
df["Product Reviews Count"] = pd.to_numeric(df["Product Reviews Count"], errors="coerce").fillna(0).astype(int)

print("Missing values after cleaning:")
print(df.isna().sum())
df.info()
df.head(5)

"""### 1.4 Clean text fields"""

df = df.drop_duplicates(subset=["Product Id"])
df = df.drop_duplicates(subset=["Product Name","Product Brand"])
df.reset_index(drop=True, inplace=True)

import re

def clean_text(s):
    if pd.isna(s): return ""
    s = str(s).lower()
    s = re.sub(r"http\S+|www\.\S+", " ", s)
    s = re.sub(r"[^a-z0-9\s\-\+]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

for col in ["Product Name","Product Brand","Product Category","Product Description","Product Tags"]:
    df[col] = df[col].astype(str).apply(clean_text)

nlp = spacy.load("en_core_web_sm")
def clean_and_extract_tags(text):
    doc = nlp(str(text).lower())
    tags = [token.text for token in doc
            if token.is_alpha and token.text not in STOP_WORDS]
    return " ".join(tags)

columns_to_extract = ["Product Category", "Product Brand", "Product Description"]
for col in columns_to_extract:
    df[col] = df[col].fillna("").apply(clean_and_extract_tags)

df["Product Tags"] = df[columns_to_extract].apply(lambda row: " ".join(row), axis=1)

df_rb = df[[
    "Product Id","Product Name","Product Brand","Product Category",
    "Product Rating","Product Reviews Count","Product Image Url"
]].copy()

df_rb["Product Rating"] = pd.to_numeric(df_rb["Product Rating"], errors="coerce").clip(0,5).fillna(0.0)
df_rb["Product Reviews Count"] = pd.to_numeric(df_rb["Product Reviews Count"], errors="coerce").fillna(0).clip(lower=0).astype(int)

df["text_features"] = (
    df["Product Name"].fillna("") + " " +
    df["Product Brand"].fillna("") + " " +
    df["Product Category"].fillna("") + " " +
    df["Product Tags"].fillna("") + " " +
    df["Product Description"].fillna("")
).str.strip()

"""## 2. Exploratory Data Analysis

### 2.1 Distribution of Product Ratings
"""

plt.figure(figsize=(6,4))
sns.histplot(df["Product Rating"], bins=20, kde=False, color="skyblue")
plt.title("Distribution of Product Ratings")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.show()

"""### 2.2 Distribution of Reviews Count

> Add blockquote


"""

plt.figure(figsize=(6,4))
sns.histplot(df["Product Reviews Count"], bins=50, color="salmon", log_scale=(True, False))
plt.title("Distribution of Reviews Count (log scale)")
plt.xlabel("Reviews Count")
plt.ylabel("Count")
plt.show()

"""### 2.3 Top 15 Product Categories



"""

plt.figure(figsize=(10,5))
top_cats = df["Product Category"].value_counts().head(15)
sns.barplot(x=top_cats.values, y=top_cats.index, palette="viridis")
plt.title("Top 15 Product Categories")
plt.xlabel("Count")
plt.ylabel("Category")
plt.show()

"""###2.4 Top 15 Brands"""

plt.figure(figsize=(10,5))
top_brands = df["Product Brand"].value_counts().head(15)
sns.barplot(x=top_brands.values, y=top_brands.index, palette="magma")
plt.title("Top 15 Product Brands")
plt.xlabel("Count")
plt.ylabel("Brand")
plt.show()

""" ### 2.5 Ratings vs. Reviews"""

plt.figure(figsize=(7,5))
sns.scatterplot(data=df, x="Product Reviews Count", y="Product Rating", alpha=0.5)
plt.xscale("log")
plt.title("Ratings vs. Reviews Count")
plt.xlabel("Reviews Count (log scale)")
plt.ylabel("Rating")
plt.show()

"""## Models

### 3.1 Popularity-Based Recommender
- Formula: weighted rating + demand
- Returns trending/highly rated products
"""

R = df_rb["Product Rating"]
v = df_rb["Product Reviews Count"]
C = R.mean()
m = np.percentile(v, 60)

weighted = (v/(v+m))*R + (m/(v+m))*C
demand = np.log1p(v)
score_raw = 0.85*weighted + 0.15*demand
df_rb["popularity_score"] = MinMaxScaler().fit_transform(score_raw.to_numpy().reshape(-1,1)).ravel()

def top_overall(k=10, min_reviews=0):
    s = df_rb[df_rb["Product Reviews Count"] >= int(min_reviews)]
    return (s.sort_values("popularity_score", ascending=False)
              .head(k)[["Product Id","Product Name","Product Brand","Product Category",
                        "Product Rating","Product Reviews Count","popularity_score","Product Image Url"]]
              .reset_index(drop=True))

def top_in_category(category, k=10, min_reviews=0):
    s = df_rb[(df_rb["Product Category"]==str(category)) &
              (df_rb["Product Reviews Count"] >= int(min_reviews))]
    return (s.sort_values("popularity_score", ascending=False)
              .head(k)[["Product Id","Product Name","Product Brand","Product Rating",
                        "Product Reviews Count","popularity_score","Product Image Url"]]
              .reset_index(drop=True))

def top_for_brand(brand, k=10, min_reviews=0):
    s = df_rb[(df_rb["Product Brand"]==str(brand)) &
              (df_rb["Product Reviews Count"] >= int(min_reviews))]
    return (s.sort_values("popularity_score", ascending=False)
              .head(k)[["Product Id","Product Name","Product Category","Product Rating",
                        "Product Reviews Count","popularity_score","Product Image Url"]]
              .reset_index(drop=True))

# Top 10 overall products (with at least 3 reviews)
print("🔹 Top 10 Overall Products (min_reviews=3)")
display(top_overall(k=10, min_reviews=3))

# Top 10 products in the most common category
example_cat = df_rb["Product Category"].mode().iloc[0]
print(f"\n🔹 Top 10 Products in Category: {example_cat} (min_reviews=3)")
display(top_in_category(example_cat, k=10, min_reviews=3))

# Top 10 products for the most common brand
example_brand = df_rb["Product Brand"].mode().iloc[0]
print(f"\n🔹 Top 10 Products for Brand: {example_brand} (min_reviews=3)")
display(top_for_brand(example_brand, k=10, min_reviews=3))

"""### 3.2 Content-Based Recommender (TF-IDF + Cosine)
- Uses product name, brand, category, description, tags
- Finds semantically similar items

"""

tfidf = TfidfVectorizer(stop_words="english", ngram_range=(1,2), min_df=2, max_features=30000)
X = tfidf.fit_transform(df["text_features"])

nn = NearestNeighbors(n_neighbors=51, metric="cosine", algorithm="brute")
nn.fit(X)

idx_by_pid = {pid: i for i, pid in enumerate(df["Product Id"])}

def recommend_by_id(product_id, k=10, same_category=True, exclude_same_brand=False):
    i = idx_by_pid[product_id]
    dist, nbr = nn.kneighbors(X[i], n_neighbors=k+1)
    nbr, dist = nbr.ravel()[1:], dist.ravel()[1:]

    mask = np.ones(len(nbr), dtype=bool)
    if same_category:
        mask &= (df.iloc[nbr]["Product Category"].to_numpy() == df.at[i,"Product Category"])
    if exclude_same_brand:
        mask &= (df.iloc[nbr]["Product Brand"].to_numpy() != df.at[i,"Product Brand"])
    nbr, dist = nbr[mask], dist[mask]

    out = df.iloc[nbr][["Product Id","Product Name","Product Brand","Product Category","Product Image Url"]].copy()
    out["similarity"] = 1 - dist[:len(out)]
    return out.reset_index(drop=True).head(k)

pid = df["Product Id"].iloc[0]
print(df.loc[idx_by_pid[pid], ["Product Name","Product Brand","Product Category"]].to_dict())
recommend_by_id(pid, k=8, same_category=True)

"""### 3.3 Graph-Based Recommender (Node2Vec)

Graph of products, brands, categories

Node2Vec embeddings

Recommend structurally related items
"""



from node2vec import Node2Vec

G = nx.Graph()
for _, row in df.iterrows():
    pid = row["Product Id"]
    pname = row["Product Name"]
    brand = row["Product Brand"]
    category = row["Product Category"]


    G.add_node(pid, type="product", name=pname)


    if brand:
        G.add_node(brand, type="brand")
        G.add_edge(pid, brand, relation="made_by")


    if category:
        G.add_node(category, type="category")
        G.add_edge(pid, category, relation="belongs_to")

print("Graph built with", G.number_of_nodes(), "nodes and", G.number_of_edges(), "edges.")

node2vec = Node2Vec(
    G,
    dimensions=64,
    walk_length=20,
    num_walks=50,
    workers=4,
    seed=42
)

model = node2vec.fit(window=10, min_count=1, batch_words=4)
print("Embedding training complete. Vocabulary size:", len(model.wv))

prod_cols = ["Product Id","Product Name","Product Brand","Product Category","Product Image Url"]
prod_df   = df[prod_cols].drop_duplicates("Product Id").set_index("Product Id")

def similar_products(product_id, topn=10):
    if product_id not in model.wv:
        raise KeyError(f"{product_id} not in embedding vocabulary")

    sims = model.wv.most_similar(product_id, topn=200)

    sims = [(nid, score) for nid, score in sims if nid in prod_df.index and nid != product_id]
    sims = sims[:topn]
    out = prod_df.loc[[nid for nid, _ in sims]].copy()
    out["similarity"] = [score for _, score in sims]
    return out.reset_index()

query_pid = df["Product Id"].iloc[0]
print("QUERY:", prod_df.loc[query_pid, "Product Name"])
display(similar_products(query_pid, topn=8))

"""### 3.4. Super-Hybrid Recommender
- Combines all signals:
   - Popularity score
  - Content similarity (TF-IDF)
  - Graph similarity (Node2Vec)
- Weighted blending for final score

"""

def _norm01(series):
    s = pd.to_numeric(series, errors="coerce").fillna(0.0)
    m, M = s.min(), s.max()
    return (s - m) / (M - m) if M > m else s*0.0

def super_hybrid_cg(
    product_id,
    k=10,
    pool_size=200,
    same_category=True,
    exclude_same_brand=False,
    w_content=0.55,
    w_graph=0.35,
    w_pop=0.10
):
    try:
        pool_content = (
            recommend_by_id(product_id, k=pool_size, same_category=False,
                            exclude_same_brand=False)[["Product Id","similarity"]]
            .rename(columns={"similarity":"sim_content"})
        )
    except Exception:
        pool_content = pd.DataFrame(columns=["Product Id","sim_content"])


    try:
        pool_graph = (
            similar_products(product_id, topn=pool_size)[["Product Id","similarity"]]
            .rename(columns={"similarity":"sim_graph"})
        )
    except Exception:
        pool_graph = pd.DataFrame(columns=["Product Id","sim_graph"])

    pool = pd.concat([pool_content, pool_graph], ignore_index=True)
    if pool.empty:
        return pd.DataFrame(columns=[
            "Product Id","Product Name","Product Brand","Product Category",
            "Product Image Url","sim_content","sim_graph","popularity","score"
        ])


    pool = (pool.groupby("Product Id", as_index=False)
                .agg({c: "max" for c in pool.columns if c != "Product Id"}))

    qrow = prod_df.loc[product_id]
    if same_category:
        pool = pool[prod_df.loc[pool["Product Id"], "Product Category"].values == qrow["Product Category"]]
    if exclude_same_brand:
        pool = pool[prod_df.loc[pool["Product Id"], "Product Brand"].values != qrow["Product Brand"]]

    pool = pool[pool["Product Id"] != product_id]
    if pool.empty:
        return pd.DataFrame(columns=[
            "Product Id","Product Name","Product Brand","Product Category",
            "Product Image Url","sim_content","sim_graph","popularity","score"
        ])

    out = prod_df.loc[pool["Product Id"]].reset_index().merge(pool, on="Product Id", how="left")
    out["popularity"] = out["Product Id"].map(pop_map).fillna(0.0)

    for col in ["sim_content","sim_graph","popularity"]:
        if col not in out.columns:
            out[col] = 0.0
        out[col] = _norm01(out[col])


    out["score"] = (w_content*out["sim_content"] +
                    w_graph  *out["sim_graph"]   +
                    w_pop    *out["popularity"])

    cols = ["Product Id","Product Name","Product Brand","Product Category",
            "Product Image Url","sim_content","sim_graph","popularity","score"]
    return out.sort_values("score", ascending=False).head(k)[cols].reset_index(drop=True)

pop_map = df_rb.set_index("Product Id")["popularity_score"]

query_pid = df["Product Id"].iloc[0]
display(super_hybrid_cg(query_pid, k=8, same_category=True, exclude_same_brand=False))



"""## Metrics"""

def _ensure_str_ids(df_like, col="Product Id"):
    if col in df_like.columns:
        df_like[col] = df_like[col].astype(str)
    return df_like

def top_overall(k=10, min_reviews=0, category=None, overfetch=200):
    cand = df_rb.copy()
    cand = _ensure_str_ids(cand, "Product Id")
    if category is not None:
        cand = cand[cand["Product Category"] == category]
    if ("Product Reviews Count" in cand.columns) and (min_reviews is not None):
        cand = cand[cand["Product Reviews Count"] >= min_reviews]
    cand = (cand.sort_values("popularity_score", ascending=False)
                 .drop_duplicates(subset=["Product Id"], keep="first"))
    return cand.head(max(k, overfetch))

def evaluate_popularity(k=10, sample_size=200, min_reviews=0,
                        rel_quantile=0.8, min_cat_size=5, fallback_topn=5):
    _ensure_str_ids(df_rb, "Product Id")
    pid_list = df_rb["Product Id"].dropna().astype(str).unique().tolist()
    sample_size = min(sample_size, len(pid_list))
    if sample_size == 0:
        return {"precision": 0.0, "ndcg": 0.0}
    sample = pd.Series(pid_list).sample(sample_size, random_state=42)
    results, skipped = [], 0
    for pid in sample:
        try:
            qrow = df_rb.loc[df_rb["Product Id"] == pid].iloc[0]
            qcat = qrow["Product Category"]
            cat_df = df_rb[df_rb["Product Category"] == qcat].copy()
            _ensure_str_ids(cat_df, "Product Id")
            if len(cat_df) < min_cat_size:
                skipped += 1
                continue
            pop_thresh = cat_df["popularity_score"].quantile(rel_quantile)
            relevant = set(cat_df.loc[cat_df["popularity_score"] >= pop_thresh, "Product Id"])
            relevant.discard(pid)
            if not relevant:
                relevant = set(cat_df.sort_values("popularity_score", ascending=False)
                                      .head(fallback_topn)["Product Id"])
                relevant.discard(pid)
                if not relevant:
                    skipped += 1
                    continue
            recs_df = top_overall(k=max(k, 100), min_reviews=min_reviews, category=qcat)
            recs_df = recs_df[recs_df["Product Id"] != pid]
            recs = [str(x) for x in recs_df["Product Id"].head(k).tolist()]
            if not recs:
                backstop = (cat_df.sort_values("popularity_score", ascending=False)
                                  .loc[cat_df["Product Id"] != pid, "Product Id"]
                                  .head(k).tolist())
                recs = backstop

            results.append({
                "precision": precision_at_k(recs, relevant, k),
                "ndcg": ndcg_at_k(recs, relevant, k)
            })
        except Exception:
            skipped += 1
            continue
    metrics_df = pd.DataFrame(results)
    overall = metrics_df.mean().to_dict() if not metrics_df.empty else {"precision": 0.0, "ndcg": 0.0}
    return overall

def evaluate_content_based(k=10, sample_size=200, same_category=True, exclude_same_brand=False):
    _ensure_str_ids(df, "Product Id")
    df_ids = df["Product Id"].dropna().astype(str).unique()
    sample_size = min(sample_size, len(df_ids))
    sample = pd.Series(df_ids).sample(sample_size, random_state=42)
    results, skipped = [], 0
    for pid in sample:
        try:
            i = idx_by_pid[pid]
            qrow = df.iloc[i]
            mask = np.ones(len(df), dtype=bool)
            if same_category:
                mask &= (df["Product Category"].to_numpy() == qrow["Product Category"])
            if exclude_same_brand:
                mask &= (df["Product Brand"].to_numpy() != qrow["Product Brand"])
            mask[i] = False
            relevant = set(df.loc[mask, "Product Id"].astype(str).tolist())
            recs_df = recommend_by_id(pid, k=k,
                                      same_category=same_category,
                                      exclude_same_brand=exclude_same_brand)
            recs = [str(x) for x in recs_df["Product Id"].dropna().tolist()]

            results.append({
                "precision": precision_at_k(recs, relevant, k),
                "ndcg": ndcg_at_k(recs, relevant, k)
            })
        except Exception:
            skipped += 1
            continue
    metrics_df = pd.DataFrame(results)
    overall = metrics_df.mean().to_dict() if not metrics_df.empty else {"precision": 0.0, "ndcg": 0.0}
    return overall

def evaluate_graph_based(k=10, sample_size=200):
    _ensure_str_ids(df, "Product Id")
    df_ids = df["Product Id"].dropna().astype(str).unique()
    sample_size = min(sample_size, len(df_ids))
    sample = pd.Series(df_ids).sample(sample_size, random_state=42)
    results, skipped = [], 0
    for pid in sample:
        try:
            i = idx_by_pid[pid]
            qrow = df.iloc[i]
            mask = (df["Product Category"].to_numpy() == qrow["Product Category"]) | \
                   (df["Product Brand"].to_numpy() == qrow["Product Brand"])
            mask[i] = False
            relevant = set(df.loc[mask, "Product Id"].astype(str).tolist())
            recs_df = similar_products(pid, topn=k)
            recs = [str(x) for x in recs_df["Product Id"].dropna().tolist()]

            results.append({
                "precision": precision_at_k(recs, relevant, k),
                "ndcg": ndcg_at_k(recs, relevant, k)
            })
        except Exception:
            skipped += 1
            continue
    metrics_df = pd.DataFrame(results)
    overall = metrics_df.mean().to_dict() if not metrics_df.empty else {"precision": 0.0, "ndcg": 0.0}
    return overall

def evaluate_superhybrid(k=10, sample_size=200, same_category=True, exclude_same_brand=False):
    _ensure_str_ids(df, "Product Id")
    _ensure_str_ids(prod_df.reset_index() if prod_df.index.name != "Product Id" else prod_df, "Product Id")
    if prod_df.index.name != "Product Id":
        prod_df.set_index("Product Id", inplace=True)
    df_ids = df["Product Id"].dropna().astype(str).unique()
    sample_size = min(sample_size, len(df_ids))
    sample = pd.Series(df_ids).sample(sample_size, random_state=42)
    results, skipped = [], 0
    for pid in sample:
        try:
            qrow = prod_df.loc[pid]
            if same_category:
                rel_mask = prod_df["Product Category"].eq(qrow["Product Category"])
            else:
                rel_mask = prod_df.index != pid
            if exclude_same_brand:
                rel_mask &= prod_df["Product Brand"].ne(qrow["Product Brand"])
            relevant = set(prod_df.loc[rel_mask].index.astype(str))
            relevant.discard(pid)
            recs_df = super_hybrid_cg(pid, k=k,
                                      same_category=same_category,
                                      exclude_same_brand=exclude_same_brand)
            recs = [str(x) for x in recs_df["Product Id"].dropna().tolist()]
            results.append({
                "precision": precision_at_k(recs, relevant, k),
                "ndcg": ndcg_at_k(recs, relevant, k)
            })
        except Exception:
            skipped += 1
            continue
    metrics_df = pd.DataFrame(results)
    overall = metrics_df.mean().to_dict() if not metrics_df.empty else {"precision": 0.0, "ndcg": 0.0}
    return overall

def _ensure_str_ids(df_like, col="Product Id"):
    if col in df_like.columns:
        df_like[col] = df_like[col].astype(str)
    return df_like

def precision_at_k(recommended, relevant, k=10):
    rec_k = recommended[:k]
    denom = max(1, min(k, len(rec_k)))
    return len(set(rec_k) & set(relevant)) / denom

def ndcg_at_k(recommended, relevant, k=10):
    dcg = 0.0
    for i, rec in enumerate(recommended[:k], start=1):
        if rec in relevant:
            dcg += 1.0 / np.log2(i + 1)
    idcg = sum(1.0 / np.log2(i + 1) for i in range(1, min(len(relevant), k) + 1))
    return dcg / idcg if idcg > 0 else 0.0

print("Popularity-Based Recommender")
pop_metrics = evaluate_popularity(k=10, sample_size=50, min_reviews=3)
print(pop_metrics)

print("\nContent-Based Recommender")
content_metrics = evaluate_content_based(k=10, sample_size=50, same_category=True)
print(content_metrics)

print("\nGraph-Based Recommender")
graph_metrics = evaluate_graph_based(k=10, sample_size=50)
print(graph_metrics)

print("\nSuper-Hybrid Recommender")
hybrid_metrics = evaluate_superhybrid(k=10, sample_size=50, same_category=True)
print(hybrid_metrics)

evaluation_results = {
    "Model": ["Popularity-Based", "Content-Based", "Graph-Based", "Super-Hybrid"],
    "Precision@10": [pop_metrics["precision"], content_metrics["precision"], graph_metrics["precision"], hybrid_metrics["precision"]],
    "NDCG@10": [pop_metrics["ndcg"], content_metrics["ndcg"], graph_metrics["ndcg"], hybrid_metrics["ndcg"]]
}

evaluation_df = pd.DataFrame(evaluation_results)

print("Model Evaluation Metrics:")
display(evaluation_df)